task_manager/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("tasks.urls", namespace="tasks")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tasks/urls.py
from django.urls import path

from tasks.views import (
    index,
    ProjectTaskListView,
    CreateTaskView,
    personal_task_list,
    ProjectTaskDetailView,
    CreateWorkerView,
    DeleteTaskView,
    ProjectTaskListFinishedView,
)

app_name = "tasks"

urlpatterns = [
    path("", index, name="index"),
    path(
        "project_tasks/",
        ProjectTaskListView.as_view(),
        name="project-tasks-list",
    ),
    path("create_task/", CreateTaskView.as_view(), name="create-task"),
    path("my_tasks/<int:pk>/", personal_task_list, name="my-tasks"),
    path(
        "project_tasks/<int:pk>/",
        ProjectTaskDetailView.as_view(),
        name="project-task-detail",
    ),
    path("create_worker/", CreateWorkerView.as_view(), name="create-worker"),
    path(
        "project_tasks/<int:pk>/delete",
        DeleteTaskView.as_view(),
        name="task-delete",
    ),
    path(
        "project_tasks/finished/",
        ProjectTaskListFinishedView.as_view(),
        name="project-tasks-finished",
    ),
]

tasks/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone


class Position(models.Model):
    name = models.CharField(max_length=63)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class TaskType(models.Model):
    name = models.CharField(max_length=63)

    def __str__(self):
        return self.name


class Worker(AbstractUser):
    position = models.ForeignKey(Position, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.first_name} {self.last_name} {self.position}"


class Task(models.Model):
    task_priority = [
        ("C", "Critical"),
        ("H", "High"),
        ("M", "Medium"),
        ("L", "Low"),
    ]

    name = models.CharField(max_length=255)
    description = models.TextField()
    deadline = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    completed_time = models.DateTimeField(null=True, default=None)
    in_progress = models.BooleanField(default=False)
    priority = models.CharField(max_length=1, choices=task_priority)
    task_type = models.ForeignKey(TaskType, on_delete=models.CASCADE)
    assignees = models.ManyToManyField(settings.AUTH_USER_MODEL)

    class Meta:
        default_related_name = "tasks"
        ordering = ["deadline"]

    def clean(self, *args, **kwargs):
        # run the base validation
        super().clean(*args, **kwargs)
        now = timezone.now()
        # Don't allow dates older than now.
        if self.deadline < now:
            raise ValidationError("Deadline date must be later than now.")

tasks/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.db.models import Q
from django.forms.widgets import DateTimeInput

from tasks.models import Task, Worker


class CreateTaskForm(forms.ModelForm):
    assignees = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.filter(~Q(first_name="")),
        widget=forms.CheckboxSelectMultiple,
        required=True,
    )

    class Meta:
        model = Task
        fields = [
            "name",
            "description",
            "deadline",
            "priority",
            "task_type",
            "assignees",
        ]
        widgets = {"deadline": DateTimeInput(attrs={"type": "datetime-local"})}


class CreateWorkerForm(UserCreationForm):
    first_name = forms.CharField(
        max_length=255, required=True, label="First name"
    )
    last_name = forms.CharField(
        max_length=255, required=True, label="Last name"
    )

    class Meta(UserCreationForm.Meta):
        model = Worker
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "email",
            "position",
        )

tasks/views.py
import datetime

from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from tasks.filters import OrderFilter
from tasks.forms import CreateTaskForm, CreateWorkerForm
from tasks.models import Task


@login_required
def index(request: HttpRequest) -> HttpResponse:
    num_task_all = Task.objects.count()
    num_task_in_progress = Task.objects.filter(in_progress=True).count()
    num_task_finished = Task.objects.filter(is_completed=True).count()

    context = {
        "num_task_all": num_task_all,
        "num_task_in_progress": num_task_in_progress,
        "num_task_finished": num_task_finished,
    }

    return render(request, "tasks/index.html", context=context)


class ProjectTaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    template_name = "tasks/project_task_all.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        tasks_not_completed = Task.objects.select_related("task_type").filter(
            is_completed=False
        )
        project_tasks_filter = OrderFilter(
            self.request.GET, queryset=tasks_not_completed
        )
        project_tasks_filter_qs = project_tasks_filter.qs
        context["filter"] = project_tasks_filter
        context["tasks"] = tasks_not_completed
        context["tasks_filter"] = project_tasks_filter_qs
        return context


class ProjectTaskListFinishedView(LoginRequiredMixin, generic.ListView):
    model = Task
    template_name = "tasks/project_task_finished.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        finished_tasks = Task.objects.filter(is_completed=True)
        participants = (
            get_user_model()
            .objects.filter(tasks__in=finished_tasks)
            .distinct()
        )
        context["finished_tasks"] = finished_tasks
        context["participants"] = participants
        return context


class CreateTaskView(LoginRequiredMixin, generic.CreateView):
    form_class = CreateTaskForm
    template_name = "tasks/create_project_task.html"
    success_url = reverse_lazy("tasks:project-tasks-list")


class DeleteTaskView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    template_name = "tasks/project_task_delete_confirm.html"
    success_url = reverse_lazy("tasks:project-tasks-list")


class ProjectTaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task
    template_name = "tasks/project_task_detail.html"
    context_object_name = "project_task"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        finished_task = Task.objects.get(pk=self.kwargs["pk"])
        participants = (
            get_user_model()
            .objects.filter(tasks__in=[finished_task])
            .distinct()
        )
        context["finished_tasks"] = finished_task
        context["participants"] = participants
        return context


class CreateWorkerView(generic.CreateView):
    form_class = CreateWorkerForm
    template_name = "tasks/create_worker.html"
    success_url = reverse_lazy("login")


@login_required
def personal_task_list(request, pk):
    to_do_tasks = Task.objects.filter(
        in_progress=False, assignees__in=[pk], is_completed=False
    )
    in_progress_tasks = Task.objects.filter(
        in_progress=True, assignees__in=[pk], is_completed=False
    )

    if request.method == "POST":
        if request.POST.get("task_id_done"):
            task_id = request.POST.get("task_id_done")
            task = Task.objects.get(id=task_id)
            task.is_completed = True
            task.in_progress = False
            task.completed_time = datetime.datetime.now()
            task.save()
        elif request.POST.get("task_id"):
            task_id = request.POST.get("task_id")
            task = Task.objects.get(id=task_id)
            task.in_progress = True
            task.save()
        return HttpResponseRedirect(request.path_info)

    context = {
        "to_do_tasks": to_do_tasks,
        "in_progress_tasks": in_progress_tasks,
    }

    return render(request, "tasks/my_tasks_page.html", context)

templates/tasks/all_tasks.html
{% extends "base.html" %}

{% block content %}
  <h1>Project tasks</h1>
  <div class="row">
    <div class="col-md-4">
      <h3>Filter tasks</h3>
      <form method="get">
        {% for field in filter.form.visible_fields %}
          <div class="form-group">
            {{ field.label_tag }} {{ field }}
          </div>
        {% endfor %}
        <button class="btn btn-primary" type="submit">Search</button>
      </form>
    </div>
    <div class="col-md-8">
      <h3>Tasks</h3>
      <table class="table">
        <thead>
          <tr>
            <th>Task ID</th>
            <th>Task name</th>
            <th>Task type</th>
            <th>Task deadline</th>
            <th>Priority</th>
          </tr>
        </thead>
        <tbody>
          {% for task in tasks_filter %}
            <tr>
              <td><a href="{% url 'tasks:project-task' task.id %}">{{ task.id }}</a></td>
              <td>{{ task.name }}</td>
              <td>{{ task.task_type }}</td>
              <td>{{ task.deadline }}</td>
              <td>{{ task.priority }}</td>
              <td><a href="{% url 'tasks:task-delete' task.id%}">Delete</a></td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

templates/tasks/create_project_task.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">Add task</h4>
        </div>
        <div class="card-body">
          <form method="post" class="form">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success">Add task</button>
            <button class="btn btn-info" onclick="window.history.back()">Move back to previous page</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/tasks/create_task.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">Create Task</h4>
        </div>
        <div class="card-body">
          <form method="post" class="form">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block mt-3">Save</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/tasks/create_worker.html
{% extends "base-fullscreen.html" %}
{% load crispy_forms_filters %}

{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <form action="" method="post" class="form">
        {% csrf_token %}
        <div class="card">
          <div class="card-header">
            <h4 class="card-title">Registration Form</h4>
          </div>
          <div class="card-body">
            {{ form|crispy }}
          </div>
          <div class="card-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
            <a href="javascript:history.back()" class="btn btn-info">Previous Page</a>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/tasks/index.html
{% extends 'base.html' %}

{% block content %}

    <div class="container-fluid py-4">
        <h2 class="text-center mb-4">Project Tasks Statistics</h2>
        <div class="row mx-auto">
            <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4 offset-xl-1">
                <div class="card">
                    <div class="card-body p-3">
                        <div class="row">
                            <div class="col-8">
                                <div class="numbers">
                                    <p class="text-sm mb-0 text-capitalize font-weight-bold">Unfinished</p>
                                    <h5 class="font-weight-bolder mb-0" style="font-size: 2.5rem">
                                        {{ num_task_all }}
                                    </h5>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
                <div class="card">
                    <div class="card-body p-3">
                        <div class="row">
                            <div class="col-8">
                                <div class="numbers">
                                    <p class="text-sm mb-0 text-capitalize font-weight-bold">In progress</p>
                                    <h5 class="font-weight-bolder mb-0" style="font-size: 2.5rem">
                                        {{ num_task_in_progress }}
                                    </h5>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
                <div class="card">
                    <div class="card-body p-3">
                        <div class="row">
                            <div class="col-8">
                                <div class="numbers">
                                    <p class="text-sm mb-0 text-capitalize font-weight-bold">Finished</p>
                                    <h5 class="font-weight-bolder mb-0" style="font-size: 2.5rem">
                                        {{ num_task_finished }}
                                    </h5>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

templates/tasks/my_tasks_page.html
{% extends "base.html" %}

{% block content %}
{% if to_do_tasks %}
  <div class="container mt-5">
    <h1 class="text-center mb-4">To Do</h1>
    <div class="row row-cols-1 row-cols-md-3 g-4">
      {% for task in to_do_tasks %}
        <div class="col">
          <div class="card h-100">
            <div class="card-body">
              <h5 class="card-title"><a href="{% url 'tasks:project-task-detail' task.id %}">{{ task.name }}</a></h5>
              <p class="card-text"><strong>Deadline:</strong> {{ task.deadline }}</p>
              <p class="card-text"><strong>Priority:</strong> <span class="{% if task.priority == 'C' %}text-danger font-weight-bold{% elif task.priority == 'H' %}text-warning{% else %}text-secondary{% endif %}">{{ task.priority }}</span></p>
            </div>
            <div class="card-footer">
              <form method="post">
                {% csrf_token %}
                <input type="hidden" name="task_id" value="{{ task.id }}">
                <button type="submit" class="btn btn-primary">Start Doing</button>
              </form>
              <a href="{% url 'tasks:project-task-detail' task.id %}" class="btn btn-secondary ms-2">Details</a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endif %}


  {% if in_progress_tasks %}
  <div class="container mt-5">
    <h1 class="text-center mb-4">In Progress</h1>
    <div class="row row-cols-1 row-cols-md-3 g-4">
      {% for task in in_progress_tasks %}
        <div class="col">
          <div class="card h-100">
            <div class="card-body">
              <h5 class="card-title"><a href="{% url 'tasks:project-task-detail' task.id %}">{{ task.name }}</a></h5>
              <p class="card-text"><strong>Deadline:</strong> {{ task.deadline }}</p>
              <p class="card-text"><strong>Priority:</strong> <span class="{% if task.priority == 'C' %}text-danger font-weight-bold{% elif task.priority == 'H' %}text-warning{% else %}text-secondary{% endif %}">{{ task.priority }}</span></p>
            </div>
            <div class="card-footer">
              <form method="post">
                {% csrf_token %}
                <input type="hidden" name="task_id" value="{{ task.id }}">
                <button type="submit" class="btn btn-success">Finish Task</button>
              </form>
              <a href="{% url 'tasks:project-task-detail' task.id %}" class="btn btn-secondary ms-2">Details</a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endif %}
{% endblock %}

templates/tasks/profile_page.html
{% extends "base.html" %}

{% block content %}
  {% if to_do_tasks %}
  <h1>To do</h1>
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Task name</th>
          <th>Task description</th>
          <th>Task deadline</th>
          <th>Priority</th>
          <th></th>
        </tr>
      </thead>
      <tbody>

      {% for task in to_do_tasks %}
        <tr>
          <td>{{ task.name }}</td>
          <td>{{ task.description }}</td>
          <td>{{ task.deadline }}</td>
          <td>{{ task.priority }}</td>
          <td>
            <form method="post">
              {% csrf_token %}
              <input type="hidden" name="task_id" value="{{ task.id }}">
              <button type="submit" class="btn btn-primary">Start doing</button>
            </form>
          </td>
        </tr>
        {% endfor %}

      </tbody>
    </table>
  {% endif %}

  {% if in_progress_tasks %}
  <h1>In progress</h1>
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Task name</th>
          <th>Task description</th>
          <th>Task deadline</th>
          <th>Priority</th>
          <th></th>
        </tr>
      </thead>
      <tbody>

      {% for task in in_progress_tasks %}
        <tr>
          <td>{{ task.name }}</td>
          <td>{{ task.description }}</td>
          <td>{{ task.deadline }}</td>
          <td>{{ task.priority }}</td>
          <td>
            <form method="post">
              {% csrf_token %}
              <input type="hidden" name="task_id_done" value="{{ task.id }}">
              <button type="submit" class="btn btn-success">Done</button>
            </form>
          </td>
        </tr>
        {% endfor %}

      </tbody>
    </table>
  {% endif %}

  {% if completed_tasks %}
   <h1>Finished</h1>
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Task name</th>
          <th>Task description</th>
          <th>Task deadline</th>
          <th>Priority</th>
          <th>Finished</th>
        </tr>
      </thead>
      <tbody>

      {% for task in completed_tasks %}
        <tr>
          <td>{{ task.name }}</td>
          <td>{{ task.description }}</td>
          <td>{{ task.deadline }}</td>
          <td>{{ task.priority }}</td>
          <td>{{ task.completed_time}}</td>
        </tr>
        {% endfor %}

      </tbody>
    </table>
  {% endif %}
{% endblock %}

templates/tasks/project_task.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-8 mx-auto">
        <h3 class="my-4">{{ project_task.name }}</h3>
        <table class="table table-striped">
          <tbody>
            <tr>
              <th scope="row">Task ID</th>
              <td>{{ project_task.id }}</td>
            </tr>
            <tr>
              <th scope="row">Task name</th>
              <td>{{ project_task.name }}</td>
            </tr>
            <tr>
              <th scope="row">Task description</th>
              <td>{{ project_task.description }}</td>
            </tr>
            <tr>
              <th scope="row">Task type</th>
              <td>{{ project_task.task_type }}</td>
            </tr>
            <tr>
              <th scope="row">Task deadline</th>
              <td>{{ project_task.deadline }}</td>
            </tr>
            <tr>
              <th scope="row">Priority</th>
              <td>{{ project_task.priority }}</td>
            </tr>
            <tr>
              <th scope="row">Participants</th>
              <td>{{ project_task.assignees.all }}</td>
            </tr>
          </tbody>
        </table>
        <div class="row justify-content-center">
          <a href="{% url 'tasks:project-tasks-list' %}" class="btn btn-primary">Back to tasks list</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/tasks/project_task_all.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-3">
      <div class="card">
        <div class="card-body">
          <form method="get">
            {% for field in filter.form.visible_fields %}
              <div class="form-group">
                {{ field.label_tag }} {{ field }}
              </div>
            {% endfor %}
            <button class="btn btn-dark" type="submit">Search</button>
          </form>
        </div>
      </div>
    </div>
    <div class="col-md-9">
      <h1 class="text-center">Project Active Tasks</h1>
      <br>
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th class="text-center">Task ID</th>
              <th class="text-center">Task name</th>
              <th class="text-center">Task type</th>
              <th class="text-center">Task deadline</th>
              <th class="text-center">Priority</th>
              <th class="text-center">Actions</th>
            </tr>
          </thead>
          <tbody>
            {% for task in tasks_filter %}
              <tr>
                <td class="text-center">{{ task.id }}</td>
                <td class="text-center">{{ task.name }}</td>
                <td class="text-center">{{ task.task_type }}</td>
                <td class="text-center">{{ task.deadline }}</td>
                <td class="text-center {% if task.priority == 'C' %}text-danger font-weight-bold{% elif task.priority == 'H' %}text-warning{% else %}text-secondary{% endif %}">
      {{ task.priority }}
                </td>
                <td>
                  <a href="{% url 'tasks:project-task-detail' task.id %}" class="btn btn-sm btn-secondary">Details</a>
                  <a href="{% url 'tasks:task-delete' task.id %}" class="btn btn-sm btn-danger">Delete</a>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="text-right">
        <a href="{% url 'tasks:create-task' %}" class="btn btn-sm btn-success">Add task</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/tasks/project_task_delete_confirm.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
    <div class="row justify-content-center mt-5">
      <div class="col-md-6">
        <div class="card">
          <div class="card-body">
            <h1 class="card-title">Delete task?</h1>
            <form action="" method="post">
              {% csrf_token %}
              <p class="card-text">Do you really want to delete Task with name: {{ task.name }}?</p>
              <br>
              <button type="submit" class="btn btn-danger mr-2">Yes</button>
              <button type="button" class="btn btn-info" onclick="window.history.back()">No, move back to previous page</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/tasks/project_task_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-8 mx-auto">
        <h3 class="text-center my-4">{{ project_task.name }}</h3>
        <table class="table table-striped">
          <tbody>
            <tr>
              <th scope="row">Task ID</th>
              <td>{{ project_task.id }}</td>
            </tr>
            <tr>
              <th scope="row">Task name</th>
              <td>{{ project_task.name }}</td>
            </tr>
            <tr>
              <th scope="row">Task description</th>
              <td>{{ project_task.description }}</td>
            </tr>
            <tr>
              <th scope="row">Task type</th>
              <td>{{ project_task.task_type }}</td>
            </tr>
            <tr>
              <th scope="row">Task deadline</th>
              <td>{{ project_task.deadline }}</td>
            </tr>
            <tr>
              <th scope="row">Priority</th>
              <td class="{% if project_task.priority == 'C' %}text-danger{% elif project_task.priority == 'H' %}text-warning{% endif %}">{{ project_task.priority }}</td>
            </tr>
            <tr>
              <th scope="row">Participants</th>
              <td>
                {% for participant in participants %}
                  <div class="d-flex justify-content-between align-items-center mb-3">
                    <div class="me-3">
                      {{ participant.first_name }} {{ participant.last_name }}
                    </div>
                  </div>
                {% endfor %}
              </td>
            </tr>
          </tbody>
        </table>
        <div class="row justify-content-center">
          <a href="javascript:history.back()" class="btn btn-info">Previous Page</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/tasks/project_task_finished.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-4">
    <div class="row">
        <h2 class="text-center mb-4">Completed Tasks</h2>
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th class="text-center">Task Name</th>
                <th class="text-center">Deadline</th>
                <th class="text-center">Priority</th>
                <th class="text-center">Completed Time</th>
                <th class="text-center">Completed By</th>
              </tr>
            </thead>
            <tbody>
              {% for task in finished_tasks %}
                <tr>
                  <td class="text-center">{{ task.name }}</td>
                  <td class="text-center">{{ task.deadline }}</td>
                  <td class="text-center">
                    {{ task.priority }}
                  </td>
                  <td class="text-center" >{{ task.completed_time }}</td>
                  <td class="text-center">
                    {% for participant in task.assignees.all %}
                      <div class="d-flex align-items-center">
                        <h7 class="mb-1">{{ participant.first_name }} {{ participant.last_name }}</h7>
                      </div>
                    {% endfor %}
                  </td>
                  <td>
                    <a href="{% url 'tasks:project-task-detail' task.id %}" class="btn btn-sm btn-secondary">Details</a>
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
    </div>
  </div>
{% endblock %}

templates/tasks/project_tasks_finished.html
{% extends "base.html" %}

{% block content %}
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Task name</th>
          <th>Task description</th>
          <th>Task deadline</th>
          <th>Priority</th>
          <th>Completed time</th>
          <th>Completed by</th>
        </tr>
      </thead>
      <tbody>
        {% for task in finished_tasks %}
          <tr>
            <td>{{ task.name }}</td>
            <td>{{ task.description }}</td>
            <td>{{ task.deadline }}</td>
            <td>{{ task.priority }}</td>
            <td>{{ task.completed_time }}</td>
            <td>
                {% for participant in participants %}
                  <div class="d-flex justify-content-between align-items-center mb-3">
                    <div class="me-3">
                      <h5 class="mb-0">{{ participant.first_name }} {{ participant.last_name }}</h5>
                    </div>
                  </div>
                {% endfor %}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

templates/tasks/task_delete_confirm.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'tasks:project-tasks-list' %}">No, back to project tasks</a>
  </form>
{% endblock %}